### ISSUE TITLE
order matters when defining pluging settings

### ISSUE THREAD

**Issue by gabtastic** [rossmcdonald/telegraf#8]
Based on the following quote in telegraf documentation, order in `mappings` should be preserved.

> NOTE: Order matters, the [inputs.cpu.tags] table must be at the end of the plugin definition.
> in https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md

and considering the following:

```
telegraf_plugins:                                                                      
  - name: net                                                                            
    options:                                                                             
      interval: 5s                                                                       
      fielddrop: ['ip_*','tcp_*','udp_*','icmp*','packets_*','drop_*','err_*']           
      fieldpass: ['bytes_*']                                                             
      tagdrop:                                                                           
        interface: [ "imq0", "imq1" ]
```

It seems that when using the `tagdrop` or `tagpass` attributes, the order is not preserved and I end up with an invalid configuration in telegraf that looks like this:

```
[[inputs.net]]
  [inputs.net.tagdrop]
      interface = [ "imq0", "imq1" ]
    fielddrop = [ "ip_*", "tcp_*", "udp_*", "icmp*", "packets_*", "drop_*", "err_*" ]
    interval = "5s"
    fieldpass = [ "bytes_*" ]
```

Expected end result should look like this:

```
[[inputs.net]]
  fielddrop = [ "ip_*", "tcp_*", "udp_*", "icmp*", "packets_*", "drop_*", "err_*" ]
  interval = "5s"
  fieldpass = [ "bytes_*" ]
  [inputs.net.tagdrop]
    interface = [ "imq0", "imq1" ]
```
